### PR TITLE
Add duecredit citation

### LINKED ISSUE #5: Add duecredit citation

### PR DESCRIPTION
**Pull request by effigies**
@yarikoptic: How does this look? And does it make more sense to put it at the module level for something this small, or to decorate the [core function](https://github.com/nipy/quickshear/blob/fe865addee727593f10584d7a1e8308571e92362/quickshear.py#L105-L138)?

I haven't dug much into `duecredit`, so I'm not really sure why you'd choose one or the other.

Closes #5.

### CODE REVIEW

**Comment by yarikoptic** [comment]
1. I would recommend to decorate with `due` the `quickshear` function so no spurious citations if someone just merely imported your module (e.g. as a part of nipype interfaces or smth like that)

2. but now that you would have two files to distribute (:-/) you would need to make a proper quickshear module with them, which would be advantageous to encourage you to get some `quickshear/tests` going ;)   Otherwise, you can't just list due.py in your setup.py since you don't want it to be distributed as a top level module/package.

Alternative dirty solution-- copy/paste `due.py` into your `quickshear.py` so you stay as 1-file-module ;)

**Comment by yarikoptic** [comment]
looks ok to me ;)  did you try on some ?  did it work? ;)
in my case on a quick trial I got it crashed:
```shell
$> ./quickshear.py /home/yoh/datalad_aside2/labs/haxby/raiders/sub001/anatomy/highres004_deface{d.nii.gz,mask.nii.gz} defaced         
Traceback (most recent call last):
  File "./quickshear.py", line 226, in <module>
    sys.exit(main(*sys.argv))
  File "./quickshear.py", line 220, in main
    new_anat = quickshear(anat_img, mask_img, opts.buffer)
  File "./quickshear.py", line 176, in quickshear
    xdiffs, ydiffs = np.diff(low)
ValueError: need more than 0 values to unpack
```

**Comment by effigies** [comment]
It's worked for me on the subjects I've tried. Could you make the brainmask available? This is an issue with the convex hull, it looks like, so I won't need the anatomical to assess.

Also, have you tried with [v1.0](https://github.com/nipy/quickshear/tree/v1.0)? I did switch to using nice numpy functions where possible, but the hand-written code might give more informative errors. (Or work and show the things I thought equivalent weren't.)

**Comment by yarikoptic** [comment]
all (well -- defaced and functionals) data is there online at http://datasets.datalad.org/?dir=/labs/haxby/raiders/sub001/anatomy/  . didn't crash with v1.0:
```shell
$> ./quickshear.py /home/yoh/datalad_aside2/labs/haxby/raiders/sub001/anatomy/highres004_deface{d.nii.gz,mask.nii.gz} defaced
Anat image axes: ('P', 'S', 'R')
Mask image axes: ('P', 'S', 'R')
Mask shape!: (256, 256, 160)
Aligning anatomical image to +x -> P
Aligning mask to +x -> P
Aligning anatomical image to +y -> S
Aligning mask to +y -> S
Defaced file: defaced
```

**Comment by effigies** [comment]
@yarikoptic I see the problem. The code originally assumed (and still does) that the axes were always `('R'/'L', 'A'/'P', 'S'/'I')`, and didn't consider permutations. I'll have to fix that...

**Comment by effigies** [comment]
Also, that defacemask is not a brainmask, which is what quickshear needs. You're probably running into an issue with the fact that it's assuming you have a roughly brain-shaped mask.

**Pull request merged**
